services:
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/foodsb
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    ports: 
      - 8080:80
    environment:
      - BACKEND_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodbcontainer
    #ports:
    # - 27018:27017 
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    restart: always
  


volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
