apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.config.NAMESPACE }}
data:
  APP_ENV: "{{ .Values.config.APP_ENV }}"
  APP_DEBUG: "{{ .Values.config.APP_DEBUG }}"
