apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-{{ .Release.Name }}
  namespace: {{ .Values.config.NAMESPACE }}
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
