apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-{{ .Release.Name }}
  namespace: helm-test
  labels:
    app: mongodb
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv
