apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: helm-test
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
