apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeremydecuypere
  labels:
    app: jeremydecuypere
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: jeremydecuypere
  template:
    metadata:
      labels:
        app: jeremydecuypere
    spec:
      containers:
      - name: backend
        image: assignment-docker-and-cloud-computing-jeremydecuypere-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000 
      - name: frontend
        image: assignment-docker-and-cloud-computing-jeremydecuypere-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 
      - name: database
        image: mongo
        ports:
        - containerPort: 27017  
