apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: assignment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: assignment
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: assignment
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
