apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-alertmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/instance: prometheus
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.27.0
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
          name: http
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: storage
          mountPath: /alertmanager
        - name: config
          mountPath: /etc/alertmanager
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-prometheus-alertmanager-0
      - name: config
        configMap:
          name: prometheus-alertmanager
