apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: default
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: alertmanager-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-prometheus-alertmanager-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
