apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
  namespace: default
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: default
    receivers:
    - name: default
