apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: default
type: Opaque
data:
  admin-user: YWRtaW4=        
  admin-password: ZFBqNGF6MmxUcDVJVWFwblNYN2p5TDhCSWJkRGVVdjd3akFoSllVeA==

