apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: default
data:
  grafana.ini: |
    [server]
    domain = 34.140.201.65
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = true
