name: Update Docker Hub Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_REPO_FRONTEND }}:latest ./frontend
        docker push ${{ secrets.DOCKER_REPO_FRONTEND }}:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_REPO_BACKEND }}:latest ./backend
        docker push ${{ secrets.DOCKER_REPO_BACKEND }}:latest

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        credentials_json: ${{ secrets.GKE_CREDENTIALS }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GKE_CREDENTIALS }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: 'kubernetesdeployment-446213'
        install_components: 'kubectl'




    - name: Trigger Google Cloud Deploy
      run: |
        gcloud deploy releases create release-$(date +%Y%m%d%H%M%S) \
          --delivery-pipeline=testenvironmentpipeline \
          --region=europe-west1 \
          --images=frontend=${{ secrets.DOCKER_REPO_FRONTEND }}:latest,backend=${{ secrets.DOCKER_REPO_BACKEND }}:latest \
          --project=kubernetesdeployment-446213
